#!/bin/bash
ip=192.168.1.106
computername=dc1
realm=my.lan
domain=my
hostnamectl set-hostname $computername
sudo sh -c "echo '$ip $computername.$realm $computername'  >>  /etc/hosts"
# stop and disable systemd-resolved service
sudo systemctl disable --now systemd-resolved
# remove the symlink file /etc/resolv.conf
sudo unlink /etc/resolv.conf
# create a new /etc/resolv.conf file
sudo touch /etc/resolv.conf
sudo sh -c "echo 'nameserver $ip'  >>  /etc/resolv.conf"
sudo sh -c "echo 'nameserver 1.1.1.1'  >>  /etc/resolv.conf"
sudo sh -c "echo 'search $realm'  >>  /etc/resolv.conf"
# add attribute immutable to the file /etc/resolv.conf
sudo chattr +i /etc/resolv.conf
sudo apt update
#install apt package nontineractive
DEBIAN_FRONTEND=noninteractive apt-get install -y acl attr samba samba-dsdb-modules samba-vfs-modules smbclient winbind libpam-winbind libnss-winbind libpam-krb5 krb5-config krb5-user dnsutils chrony net-tools
# stop and disable samba services - smbd, nmbd, and winbind
sudo systemctl disable --now smbd nmbd winbind
# activate samba-ad-dc service
sudo systemctl unmask samba-ad-dc
# enable samba-ad-dc service
sudo systemctl enable samba-ad-dc
# backup default Samba configuration file
sudo mv /etc/samba/smb.conf /etc/samba/smb.conf.orig
sudo samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm=$realm --domain=$domain --adminpass=Password2022!
#sudo samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm=my.lan --domain=my --adminpass=Password2022!
#change dns forwarder
sudo sh -c "sed -i 's/dns forwarder = $ip/dns forwarder =1.1.1.1/g' /etc/samba/smb.conf"
# rename default Kerberos configuration to krb5.conf.orig
sudo mv /etc/krb5.conf /etc/krb5.conf.orig
# copy the Kerberos configuration generated by the samba-tool
sudo cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
# start samba-ad-dc service
sudo systemctl start samba-ad-dc
